namespace ServiceStackGen.Tests.Examples
{
    public class ClassWith2Methods
    {
        /// <summary>
        /// Should be generated by default
        /// </summary>
        public void FooBar()
        {
            
        }

        /// <summary>
        /// Should be generated by default
        /// </summary>
        public void BarFoo()
        {

        }
    }
}
