namespace ServiceStackGen.Tests.Examples
{
    public abstract class AbstractClass
    {
        /// <summary>
        /// Should get ignored by default
        /// </summary>
        public void AMethod()
        {
            
        }
    }
    public class ClassAndVariousMethods
    {
        /// <summary>
        /// Should be generated by default
        /// </summary>
        public void BMethod()
        {
            
        }

        /// <summary>
        /// Should get ignored by default
        /// </summary>
        private void CMethod()
        {
            
        }

        /// <summary>
        /// Should be generated by default
        /// </summary>
        public void EMethod()
        {

        }
    }
}
